# Change these first
owner: vikas111981 # Your GitHub organization or username, where this repository lives
repo: NGLUptimeMonitor # The name of this repository

sites:
  - name: "NGL.Com - New York"
    url: https://nangilife.com
    type: globalping
    check: "icmp-ping"   # Standard Ping (Latency)
    location: "New York"

  - name: "NGL.Com - London"
    url: https://nangilife.com
    type: globalping
    check: "icmp-ping"
    location: "London"

  - name: "NGL.Com - Berlin"
    url: https://nangilife.com
    type: globalping
    check: "icmp-ping"
    location: "Berlin"

  - name: "NGL.Com - New Delhi"
    url: https://nangilife.com
    type: globalping
    check: "icmp-ping"
    location: "New Delhi" #

  - name: "NGL.Com - Mumbai"
    url: https://nangilife.com
    type: globalping
    check: "icmp-ping"
    location: "Mumbai" #

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /NGLUptimeMonitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: NGLUptimeMonitor
  introTitle: "**NGLUptimeMonitor** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
